### ISSUE TITLE
Dashboard counts are incorrect

### ISSUE THREAD

**Issue by briangow** [chorus-ai/chorus-container-apps#31]
When using the data dashboard earlier this month, I noticed that some of the file counts are incorrect. 

For example, my records indicate that MIT submitted 4272 waveform records and the data dashboard shows 2948. The situation for Pitt seems even further off, it only lists 61 waveform records on the dashboard but they have 2101 records in their 20240618 folder by my count.

@tcpan & @jshoughtaling expect that not all of the files are being indexed.

**Comment by jshoughtaling** [comment]
@briangow & @tcpan  - was an issue with how I was iterating and setting indices. I've fixed the issue in this [commit](https://github.com/chorus-ai/chorus-container-apps/commit/0c90cdb35ffc9ccc95e309745811eb933025a1e0)

**Comment by jshoughtaling** [comment]
@briangow and @tcpan - the issue required additional refactor. I now no longer use pandas and instead write csv files to a temp location that I send off to the central postgres instance after processing each site. I also updated the dashboard to reference samples of the file metadata rather than the 4M+ files (causing the dashboard to crash). The latest version should be stable and show the correct information.
